### ISSUE TITLE
ImportError: cannot import name 'pub'

### ISSUE THREAD

**Issue by opentheibm** [Denton24646/Titan#29]
D:\Anaconda3\python.exe D:/mypython/mys/titan/titan_app.py
Traceback (most recent call last):
  File "D:/mypython/mys/titan/titan_app.py", line 5, in <module>
    from core import titan_main
  File "D:\mypython\mys\titan\core\titan_main.py", line 2, in <module>
    from strategies import poc_strategy
  File "D:\mypython\mys\titan\strategies\poc_strategy.py", line 2, in <module>
    from strategies.base_strategy import BaseStrategy
  File "D:\mypython\mys\titan\strategies\base_strategy.py", line 1, in <module>
    from core.markets import market_watcher
  File "D:\mypython\mys\titan\core\markets\market_watcher.py", line 5, in <module>
    from core.markets import ticker
  File "D:\mypython\mys\titan\core\markets\ticker.py", line 2, in <module>
    from pubsub import pub
ImportError: cannot import name 'pub'

**Comment by sdmr** [comment]
If you do pip install pypubsub which will resolve the issue
